### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by danrobi11** [fastrizwaan/mpv_flatpak#1]
Im following the readme guide. 

```
Error: Error moving file /home/danrobi/mpv_flatpak/.flatpak-builder/rofiles/rofiles-AuD2CO/files/share/applications/mpv.desktop: No such file or directory
```

Devuan beowulf
4.19.0-16-amd64

**Comment by fastrizwaan** [comment]
please, wait I'm trying to add it to flathub https://github.com/flathub/flathub/pull/2301

**Comment by fastrizwaan** [comment]
The build succeeded, to test this build, install it from the testing repository:
flatpak install https://dl.flathub.org/build-repo/44929/io.mpv.Mpv.flatpakref

**Comment by danrobi11** [comment]
Does work with  `flatpak install --user https://dl.flathub.org/build-repo/44929/io.mpv.Mpv.flatpakref`

Flatpak 1.2.5

Very nice ! Thank you much !! 
Therefore closing
